# Generated by Django 5.0.7 on 2024-10-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='upload_product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_t', models.TextField(max_length=200)),
                ('product_n', models.TextField(max_length=100)),
                ('product_p', models.IntegerField()),
                ('product_d', models.IntegerField()),
                ('product_i', models.ImageField(upload_to='products')),
                ('product_c', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
